database:
  host: ${DATABASE_HOST:jdbc:mysql://localhost:3306}
  name: ${DATABASE_NAME:learning_catalogue}
  use-ssl: ${DATABASE_USESSL:false}
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  resources:
    add-mappings: false
  datasource:
    url: ${DATASOURCE_URL:${database.host}/${database.name}?useSSL=${database.use-ssl}&requireSSL=false}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:my-secret-pw}
    platform: mysql
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  servlet:
    multipart:
      max-file-size: 5120MB
      max-request-size: 5120MB

server:
  port: 9001

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    com.zaxxer.hikari: ERROR
    org:
      springframework:
        data:
          elasticsearch:
            core: ${ROOT_LOGGING_LEVEL:INFO}

elasticsearch:
  protocol: ${ES_PROTOCOL:http}
  host: ${ES_HOST:localhost}
  port: ${ES_PORT:9200}
  username: ${ELASTICSEARCH_USERNAME:elastic}
  password: ${ELASTICSEARCH_PASSWORD:changeme}
  readTimeout: ${ELASTICSEARCH_READ_TIMEOUT:10000}
  repositories:
    courses:
      indexName: "courses"

rustici:
  e-learning-manifests: ${ELEARNING_MANIFESTS:imsmanifest.xml,tincan.xml}
  url: ${RUSTICI_URL:http://csl.local/rustici}
  api-url: "${rustici.url}/RusticiEngine/api/v2"
  username: ${RUSTICI_USERNAME:apiuser}
  password: ${RUSTICI_PASSWORD:password}
  tenant: ${RUSTICI_TENANT:default}

azure:
  account:
    name: ${AZURE_ACCOUNT_NAME:devstoreaccount1}
    key: ${AZURE_ACCOUNT_KEY:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==}
  storage:
    container: ${AZURE_STORAGE_CONTAINER:lpgdevcontent}
    scorm-container: ${AZURE_STORAGE_SCORM_CONTAINER:rustici}
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=${azure.account.name};AccountKey=${azure.account.key}}
  scorm-cdn: "${rustici.url}/cdn"

management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: "*"
        allowed-methods: "GET, PUT, POST, DELETE, OPTIONS"

record:
  serviceUrl: ${LEARNER_RECORD_URL:http://localhost:9000}
  eventUrlFormat: "${record.serviceUrl}/event/%s"
  bulkEventsUrl: "${record.serviceUrl}/events-list"
  bookingUrlFormat: "${record.eventUrlFormat}/booking"

registry:
  serviceUrl: ${REGISTRY_SERVICE_URL:http://localhost:9002}
  getCurrentUrl: "${registry.serviceUrl}/civilServants/me"
  getOrganisationalUnit: "${registry.serviceUrl}/organisationalUnits/parent/%s"
  getAllCodes: "${registry.serviceUrl}/organisationalUnits/allCodesMap"

oauth:
  serviceUrl: ${OAUTH_SERVICE_URL:http://localhost:8080}
  clientId: ${CLIENT_ID:9fbd4ae2-2db3-44c7-9544-88e80255b56e}
  clientSecret: ${CLIENT_SECRET:test}
  checkTokenEndpoint: ${OAUTH_CHECK_TOKEN_ENDPOINT:/oauth/check_token}
  checkTokenUrl: "${oauth.serviceUrl}${oauth.checkTokenEndpoint}"
  tokenEndpoint: ${OAUTH_TOKEN_ENDPOINT:/oauth/token}
  tokenUrl: "${oauth.serviceUrl}${oauth.tokenEndpoint}"
  maxTotalConnections: 200
  defaultMaxConnectionsPerRoute: 100
  maxPerServiceUrl: 100
  jwtKey: ${jwt_key}

retention:
  timeInDays: ${RETENTION_TIME_IN_DAYS:90}
